<?php

/**
 * BaseMedico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $registro_medico
 * @property string $nombre
 * @property string $apellido
 * @property string $especialidad
 * @property string $email
 * @property Doctrine_Collection $Citas
 * 
 * @method string              getRegistroMedico()  Returns the current record's "registro_medico" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method string              getApellido()        Returns the current record's "apellido" value
 * @method string              getEspecialidad()    Returns the current record's "especialidad" value
 * @method string              getEmail()           Returns the current record's "email" value
 * @method Doctrine_Collection getCitas()           Returns the current record's "Citas" collection
 * @method Medico              setRegistroMedico()  Sets the current record's "registro_medico" value
 * @method Medico              setNombre()          Sets the current record's "nombre" value
 * @method Medico              setApellido()        Sets the current record's "apellido" value
 * @method Medico              setEspecialidad()    Sets the current record's "especialidad" value
 * @method Medico              setEmail()           Sets the current record's "email" value
 * @method Medico              setCitas()           Sets the current record's "Citas" collection
 * 
 * @package    clinicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('medico');
        $this->hasColumn('registro_medico', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('apellido', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('especialidad', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cita as Citas', array(
             'local' => 'id',
             'foreign' => 'medico_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}