<?php

/**
 * BaseCita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $paciente_id
 * @property integer $medico_id
 * @property date $fecha
 * @property time $hora
 * @property string $motivo
 * @property string $estado
 * @property Paciente $Paciente
 * @property Medico $Medico
 * 
 * @method integer  getPacienteId()  Returns the current record's "paciente_id" value
 * @method integer  getMedicoId()    Returns the current record's "medico_id" value
 * @method date     getFecha()       Returns the current record's "fecha" value
 * @method time     getHora()        Returns the current record's "hora" value
 * @method string   getMotivo()      Returns the current record's "motivo" value
 * @method string   getEstado()      Returns the current record's "estado" value
 * @method Paciente getPaciente()    Returns the current record's "Paciente" value
 * @method Medico   getMedico()      Returns the current record's "Medico" value
 * @method Cita     setPacienteId()  Sets the current record's "paciente_id" value
 * @method Cita     setMedicoId()    Sets the current record's "medico_id" value
 * @method Cita     setFecha()       Sets the current record's "fecha" value
 * @method Cita     setHora()        Sets the current record's "hora" value
 * @method Cita     setMotivo()      Sets the current record's "motivo" value
 * @method Cita     setEstado()      Sets the current record's "estado" value
 * @method Cita     setPaciente()    Sets the current record's "Paciente" value
 * @method Cita     setMedico()      Sets the current record's "Medico" value
 * 
 * @package    clinicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCita extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cita');
        $this->hasColumn('paciente_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('medico_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hora', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('motivo', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('estado', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'pendiente',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Paciente', array(
             'local' => 'paciente_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Medico', array(
             'local' => 'medico_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}