<?php

/**
 * PacienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paciente');
    }
}